version: '2.2'
services:
  database:
    image: "postgres:13.4"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ~/.psqlrc:/etc/postgresql-common/psqlrc
      - ~/.psql_history:/root/.psql_history
    ports:
      - 5432:5432

volumes:
  database-data:
