version: '2.2'
services:
  database:
    image: "postgres:13"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  database-data:
